export const ADD_TODO = 'ADD_TODO';
export const DELETE_TODO = 'DELETE_TODO';
export const EDIT_TODO = 'EDIT_TODO';
export const COMPLETE_TODO = 'COMPLETE_TODO';
export const COMPLETE_ALL = 'COMPLETE_ALL';
export const CLEAR_COMPLETED = 'CLEAR_COMPLETED';

export const WILL_OPEN_SOCKET = 'WILL_OPEN_SOCKET'
export const DID_OPEN_SOCKET = 'DID_OPEN_SOCKET'

export const REQUEST_FILES = 'REQUEST_FILES';
export const RECIEVE_FILES = 'RECIEVE_FILES';

export const WILL_WATCH_FILE = 'WILL_WATCH_FILE'
export const DID_WATCH_FILE = 'DID_WATCH_FILE'
export const DID_UNWATCH_FILE = 'DID_UNWATCH_FILE'
export const CHANGE_FILE = 'CHANGE_FILE'